spring.application.name=blackjack

# Configuració de MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/blackjack

# Configuració de R2DBC per a MySQL
spring.r2dbc.url=r2dbc:mysql://usuari:contrasenya@localhost:3306/blackjack
spring.r2dbc.username=root
spring.r2dbc.password=xyz1423!

server.port=8080

