spring.application.name=blackjack

# Configuració de MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/blackjack

# Configuració de R2DBC per a MySQL
spring.r2dbc.url=r2dbc:mysql://usuari:contrasenya@localhost:3306/nombre_de_la_base_de_dades
spring.r2dbc.username=usuari
spring.r2dbc.password=contrasenya

